"""inference_providers.py

Provider-agnostic router for the EC-04 / EC-06 / EC-09 Phase 3 inference
modules. Given a model name it selects the correct SDK/client and returns the
model's raw text plus (when available) token-level logprobs.

Why this exists
---------------
Previously every EC inference module (ec04/ec06/ec09) hard-coded the OpenAI
Responses API, so a Phase 1 record generated by Claude / Gemini / Grok was still
ethically judged by GPT. This module lets the gate run the SAME model that
produced the Phase 1 record, so we measure each model's OWN ethical reasoning.

Provider detection by model name
--------------------------------
  - contains "claude"  -> Anthropic   (ANTHROPIC_API_KEY)
  - contains "gemini"  -> Google      (GEMINI_API_KEY,  google-genai SDK)
  - contains "grok"    -> xAI         (XAI_API_KEY,     OpenAI-compatible)
  - everything else (incl. "gpt...")  -> OpenAI         (OPENAI_API_KEY)

Logprobs
--------
Only the OpenAI Responses API returns token logprobs here. For Anthropic /
Gemini / xAI, ``token_logprobs`` is ``None`` and a warning string explains why.
All callers already treat ``token_logprobs`` as optional, so the per-module
confidence analysis degrades gracefully.

Public surface
--------------
    detect_provider(model) -> str          # raises on empty/unrecognized name
    get_client(model) -> client            # raises clear errors on missing key/SDK
    call_model_text(client, model, system_prompt, user_prompt)
        -> (text, token_logprobs, warning, usage)
"""

from __future__ import annotations

import os
from typing import Any, Dict, List, Optional, Tuple

XAI_BASE_URL = "https://api.x.ai/v1"

# Non-OpenAI providers require an explicit max_tokens; the structured EC answers
# are short, but keep headroom for the free-text reasoning that precedes them.
ANTHROPIC_MAX_TOKENS = int(os.getenv("EC_INFERENCE_ANTHROPIC_MAX_TOKENS", "1024"))
XAI_MAX_TOKENS = int(os.getenv("EC_INFERENCE_XAI_MAX_TOKENS", "1024"))


def _get(obj: Any, key: str, default: Any = None) -> Any:
    """Attr-or-dict accessor so we can read SDK objects and plain dicts alike."""
    if obj is None:
        return default
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)


def _int_or_none(value: Any) -> Optional[int]:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _normalize_usage(
    prompt: Any, completion: Any, total: Any = None
) -> Optional[Dict[str, Optional[int]]]:
    """Normalize provider-specific usage counters into a common shape.

    Returns ``{"prompt_tokens", "completion_tokens", "total_tokens"}`` or
    ``None`` when the provider reported nothing usable. ``total_tokens`` is
    derived from prompt+completion when the provider omits it.
    """
    p = _int_or_none(prompt)
    c = _int_or_none(completion)
    t = _int_or_none(total)
    if t is None and (p is not None or c is not None):
        t = (p or 0) + (c or 0)
    if p is None and c is None and t is None:
        return None
    return {"prompt_tokens": p, "completion_tokens": c, "total_tokens": t}


# ---------------------------------------------------------------------------
# Provider detection
# ---------------------------------------------------------------------------
# OpenAI-family name markers. Detection is substring/prefix based so it
# tolerates dated ids. Unlike the previous behavior, an UNRECOGNIZED name now
# raises instead of silently defaulting to OpenAI (that silent default was one
# of the contamination-bug-class vectors: a mistyped or novel model id would be
# quietly judged by GPT).
_OPENAI_MARKERS = ("gpt", "chatgpt", "davinci", "babbage")
_OPENAI_PREFIXES = ("o1", "o3", "o4")


def detect_provider(model: Optional[str]) -> str:
    """Map a model name to a provider id.

    Detection is substring-based and case-insensitive so it tolerates dated
    model ids (e.g. "claude-3-5-sonnet-20241022", "gemini-2.5-flash",
    "grok-4", "gpt-5.4-nano").

    Raises ``ValueError`` on an empty/None name or an unrecognized name rather
    than defaulting to OpenAI, so a misrouted model fails loudly instead of
    silently being evaluated by GPT.
    """
    m = (model or "").strip().lower()
    if not m:
        raise ValueError(
            "detect_provider: no model name provided. Pass the explicit model "
            "being tested (e.g. 'claude-sonnet-4-6', 'gemini-2.5-flash', "
            "'grok-3', 'gpt-5.4-nano')."
        )
    if "claude" in m:
        return "anthropic"
    if "gemini" in m:
        return "google"
    if "grok" in m:
        return "xai"
    if any(marker in m for marker in _OPENAI_MARKERS) or any(
        m.startswith(prefix) for prefix in _OPENAI_PREFIXES
    ):
        return "openai"
    raise ValueError(
        f"detect_provider: unrecognized model name {model!r}. No provider could "
        "be inferred. Recognized markers: 'claude' (Anthropic), 'gemini' "
        "(Google), 'grok' (xAI), or an OpenAI name (e.g. 'gpt-*', 'o1*', "
        "'o3*'). Refusing to silently default to OpenAI."
    )


# ---------------------------------------------------------------------------
# Client construction (one per provider)
# ---------------------------------------------------------------------------
def _openai_client():
    try:
        from openai import OpenAI
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "The 'openai' package is not installed. Install with: pip install openai"
        ) from exc
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is not set. In PowerShell run:\n"
            '    $env:OPENAI_API_KEY = "sk-..."'
        )
    return OpenAI(api_key=api_key)


def _anthropic_client():
    try:
        import anthropic
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "The 'anthropic' package is not installed. Install with: pip install anthropic"
        ) from exc
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY is not set. In PowerShell run:\n"
            '    $env:ANTHROPIC_API_KEY = "sk-ant-..."'
        )
    return anthropic.Anthropic(api_key=api_key)


def _google_client():
    try:
        from google import genai
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "The 'google-genai' package is not installed. "
            "Install with: pip install google-genai"
        ) from exc
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GEMINI_API_KEY is not set. In PowerShell run:\n"
            '    $env:GEMINI_API_KEY = "..."'
        )
    return genai.Client(api_key=api_key)


def _xai_client():
    try:
        from openai import OpenAI
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "The 'openai' package is not installed (required for the xAI "
            "OpenAI-compatible endpoint). Install with: pip install openai"
        ) from exc
    api_key = os.getenv("XAI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "XAI_API_KEY is not set. In PowerShell run:\n"
            '    $env:XAI_API_KEY = "xai-..."'
        )
    return OpenAI(api_key=api_key, base_url=XAI_BASE_URL)


def get_client(model: Optional[str] = None):
    """Build the SDK client appropriate for ``model``'s provider."""
    provider = detect_provider(model)
    if provider == "anthropic":
        return _anthropic_client()
    if provider == "google":
        return _google_client()
    if provider == "xai":
        return _xai_client()
    return _openai_client()


# ---------------------------------------------------------------------------
# OpenAI Responses API + logprob capture
# ---------------------------------------------------------------------------
def _create_with_logprobs(client, model: str, messages: List[Dict[str, str]]):
    """Try to request token logprobs, degrading gracefully across SDK variants."""
    attempts = [
        {"top_logprobs": 5, "include": ["message.output_text.logprobs"]},
        {"top_logprobs": 5},
        {"logprobs": True, "top_logprobs": 5},
    ]
    last_exc: Optional[Exception] = None
    for extra in attempts:
        try:
            return client.responses.create(model=model, input=messages, **extra), None
        except Exception as exc:  # noqa: BLE001 - probe which kwargs the SDK accepts
            last_exc = exc
    return None, last_exc


def extract_token_logprobs(response: Any) -> Optional[List[Dict[str, Any]]]:
    """Flatten the Responses-API output into [{token, logprob}, ...] in order."""
    try:
        flat: List[Dict[str, Any]] = []
        for item in _get(response, "output", []) or []:
            for content in _get(item, "content", []) or []:
                for lp in _get(content, "logprobs", []) or []:
                    tok = _get(lp, "token")
                    val = _get(lp, "logprob")
                    if tok is not None and val is not None:
                        flat.append({"token": tok, "logprob": float(val)})
        return flat or None
    except Exception:  # noqa: BLE001 - never let logprob parsing break the run
        return None


def _openai_usage(response: Any) -> Optional[Dict[str, Optional[int]]]:
    usage = _get(response, "usage")
    if usage is None:
        return None
    return _normalize_usage(
        _get(usage, "input_tokens"),
        _get(usage, "output_tokens"),
        _get(usage, "total_tokens"),
    )


def _call_openai(
    client, model: str, system_prompt: str, user_prompt: str
) -> Tuple[str, Optional[List[Dict[str, Any]]], Optional[str], Optional[Dict[str, Optional[int]]]]:
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    warning: Optional[str] = None
    response, exc = _create_with_logprobs(client, model, messages)
    if response is None:
        warning = (
            f"logprobs unavailable ({exc.__class__.__name__}: {exc}); "
            "retried without logprobs"
        )
        response = client.responses.create(model=model, input=messages)
    text = (_get(response, "output_text") or "").strip()
    token_logprobs = extract_token_logprobs(response)
    if token_logprobs is None and warning is None:
        warning = "logprobs requested but none returned by the API"
    return text, token_logprobs, warning, _openai_usage(response)


# ---------------------------------------------------------------------------
# Anthropic / Google / xAI (no logprobs)
# ---------------------------------------------------------------------------
def _call_anthropic(
    client, model: str, system_prompt: str, user_prompt: str
) -> Tuple[str, Optional[List[Dict[str, Any]]], Optional[str], Optional[Dict[str, Optional[int]]]]:
    response = client.messages.create(
        model=model,
        max_tokens=ANTHROPIC_MAX_TOKENS,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )
    parts: List[str] = []
    for block in _get(response, "content", []) or []:
        if _get(block, "type", "text") == "text":
            text = _get(block, "text")
            if text:
                parts.append(text)
    usage = _get(response, "usage")
    usage_norm = (
        _normalize_usage(
            _get(usage, "input_tokens"), _get(usage, "output_tokens")
        )
        if usage is not None
        else None
    )
    return (
        "".join(parts).strip(),
        None,
        "logprobs not supported by the Anthropic Messages API",
        usage_norm,
    )


def _call_google(
    client, model: str, system_prompt: str, user_prompt: str
) -> Tuple[str, Optional[List[Dict[str, Any]]], Optional[str], Optional[Dict[str, Optional[int]]]]:
    # The Gemini SDK handles system context differently; prepend it to the
    # user prompt as a single string (same approach as phase5_reflection_gemini).
    combined = f"{system_prompt}\n\n{user_prompt}"
    response = client.models.generate_content(model=model, contents=combined)
    text = (_get(response, "text") or "").strip()
    meta = _get(response, "usage_metadata")
    usage_norm = (
        _normalize_usage(
            _get(meta, "prompt_token_count"),
            _get(meta, "candidates_token_count"),
            _get(meta, "total_token_count"),
        )
        if meta is not None
        else None
    )
    return text, None, "logprobs not supported by the Gemini SDK", usage_norm


def _call_xai(
    client, model: str, system_prompt: str, user_prompt: str
) -> Tuple[str, Optional[List[Dict[str, Any]]], Optional[str], Optional[Dict[str, Optional[int]]]]:
    response = client.chat.completions.create(
        model=model,
        max_tokens=XAI_MAX_TOKENS,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )
    text = ""
    choices = _get(response, "choices", []) or []
    if choices:
        message = _get(choices[0], "message")
        text = (_get(message, "content") or "").strip()
    usage = _get(response, "usage")
    usage_norm = (
        _normalize_usage(
            _get(usage, "prompt_tokens"),
            _get(usage, "completion_tokens"),
            _get(usage, "total_tokens"),
        )
        if usage is not None
        else None
    )
    return text, None, "logprobs not requested from the xAI chat endpoint", usage_norm


def call_model_text(
    client, model: str, system_prompt: str, user_prompt: str
) -> Tuple[str, Optional[List[Dict[str, Any]]], Optional[str], Optional[Dict[str, Optional[int]]]]:
    """Dispatch a single completion to the right provider.

    Returns ``(raw_text, token_logprobs, warning, usage)``. ``token_logprobs``
    is only populated for OpenAI; otherwise it is ``None`` with an explanatory
    warning. ``usage`` is a normalized
    ``{"prompt_tokens", "completion_tokens", "total_tokens"}`` dict when the
    provider reports token counts, else ``None``.
    """
    provider = detect_provider(model)
    if provider == "anthropic":
        return _call_anthropic(client, model, system_prompt, user_prompt)
    if provider == "google":
        return _call_google(client, model, system_prompt, user_prompt)
    if provider == "xai":
        return _call_xai(client, model, system_prompt, user_prompt)
    return _call_openai(client, model, system_prompt, user_prompt)
